//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.10 at 02:37:18 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://company.com/myloyal", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.company.myloyal;
